name: Terratest
'on':
  push:
    branches:
      - master

permissions: read-all

env:
  TERRAFORM_VERSION: 1.3.1
  GO_VERSION: 1.18
  AWS_REGION: "us-west-2"

# Set to the repository name
concurrency: terraform-aws-efs

jobs:
  build:
    name: Test EFS Module
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Setup Terraform  
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run the Tests
        run: cd ./test; go test -v
